# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Ruben Dedman   
title: Network Automation Consultant 
email: rubendedman@gmail.com 
# email_title: Email (Email title override)
phone: 520-330-2566  
# phone_title: Phone (Phone title override)
website: www.devmannet.com 
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: radmanded 
stackoverflow_username: "18175188"
linkedin_username: ruben-dedman
youtube_username: https://www.youtube.com/c/RubenDedman

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  
  I am a dedicated problem solver focused on digital transformation. I have over ten years of experience in IT. I am a strong believer in the power of open source software and marveled at my involvement in the modern network. I have a never-quit attitude toward learning and am always looking for new challenges. My duties involve working directly with CEOs, upper management, developers, and engineers to drive <mark> digital transformation</mark> in their businesses.
  
Check out one of my projects that Cisco published - https://developer.cisco.com/codeexchange/github/repo/Procellis-Technology-Inc/MCPiP/


content:
  - title: Certifications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: middle 
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title:  
        link_text: github 
        additional_links:
          - title:  
            icon: 
            url: 
          - title: 
            icon: 
            url: 
        quote: 
        description: | # this will include new lines to allow paragraphs
          - AWS Certified Cloud Practitioner
          - CCNA Cisco Certified Network Associate
          - CMNA Meraki Certified Network Associate
          - Black Belt Distribution Success Presales
          - Black Belt Distribution Cisco Designed for Business Presales
          - Black Belt Distribution Enterprise Networking Presales


  - title: Experience
    layout: list
    content:
      - layout: right
        title: TD SYNNEX, Remote 
        sub_title: Network Automation Consultant 
        caption: Sep 2021 - present
        link: 
        quote: 
        description: | # this will include new lines to allow paragraphs
          - Built Cisco DevNet enablement practice, certifications/specialization roadmaps, training materials, gtm, labs, and documentation
          - Developed Python API for automating Cisco/Meraki/Webex/Security/DNA-C/ACI - Over 30 use-cases
          - Retained high value($50 Mil/Year), disgruntled partners through customer obsession and service
          - Lead workshops, training, webinars and mentoring for internal and external leaders and teams

  - title: 
    layout: list
    content:
      - layout: right
        title: WhiteSky Communications LLC, Torrance, CA 
        sub_title: Network Engineer  
        caption: Jan 2020 - Apr 2021 
        link: 
        quote: 
        description: | # this will include new lines to allow paragraphs
          - Design, build, and troubleshoot 5,10,40, and 100 Gigabit fiber DWDM Wavelengths, Dark Fiber, EVPL, and circuits from most major ISPs and transit providers 
          - Managed Data Center infrastructure and campus network design for multiple data centers and multiple client networks 
          - Introduced network automation tools and python scripts for network management 
          - Worked with Juniper MX/EX, Cisco Catalyst/Nexus, Linux servers, and SD-WAN 

  - title: 
    layout: list
    content:
      - layout: right
        title: Boingo, Los Angeles, CA 
        sub_title: Cisco Field Engineer 
        caption: Jul 2020 - Dec 2020 
        link: 
        quote: 
        description: | # this will include new lines to allow paragraphs
          - Perform hands-on hardware break-fix for LAX Airport, John Wayne Airport, and Hollywood Bowl 
          - Install, repair, and maintain Cisco Wireless infrastructure, Fiber backbones from MDF to IDFs, Cisco Wireless Controller 8540, 5520, Wifi 6, Cisco 1900, 910, 3702i/e APs, Cisco 3750, 3560-CX switches, and UPS 
          - Utilize and monitor Jira ticketing system to manage projects, trouble tickets, and  tracking 
          - Analyze, interpret, and update documents and blueprints using Revu Bluebeam software 

  - title: 
    layout: list
    content:
      - layout: right
        title: DakotaPro, Tucson, AZ 
        sub_title: Network Engineer 
        caption: Jul 2018 - Jul 2019
        link: 
        quote: 
        description: | # this will include new lines to allow paragraphs
          - Design network and tower infrastructure topologies, build network in staging area, configure all equipment remotely, manage technicians in deployment, document all processes
          - Manage Network with over 5000 devices via SolarWinds, SD-WAN/UNMS, AirControl, ticket system, and other 72 troubleshooting platforms and protocols. Upgrade routers, switches, radios, and firewalls. 
          - Work with brands like Cisco, Ubiquiti, Adtran, Vayatta, Mikrotik, Ruckus, and Fortinet. Configuring, Upgrade/Update, and troubleshooting firewalls, VPNs, routers, switches, access points, cameras, UPS, VOIP, radios, firmware, OSPF, PPPoE, banners, TACACS, and AAA authentication 

  - title: Technologies  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title:  
        link_text: 
        additional_links:
          - title:  
            icon: 
            url: 
          - title: 
            icon: 
            url: 
        quote: 
        description: | # this will include new lines to allow paragraphs
          - Python, Node.js, Ansible, Terraform, Docker, AWS, GCP, Git/Github/Git, CI/CD Pipeline 
          - AI Chatbot with Dialogflow
          - Zero touch provisioning with YAML/YANG/RESTCONF/NETCONF 
          - Integrations with API, ETL with Python and JSON 
          - Webex and OAuth2 integration 
          - Cisco Catalyst/Nexus/ACI/DNA-C/SD-WAN, Juniper, Meraki, and Linux
          - Layer 3 Technologies, Layer 2 Technologies, Layer 1 Technologies
          - Commerce lifecycle API automating for on-boarding, provisioning, deprovisioning, renewals, consumption, and billing
          - Documentation with Sphinx, Readthedocs, and Jekyll using markdown
          - Web app development with Ruby, Flask, ngrok, and Jinja2 
  
  - title: Teaching, Workshops, Team Building  # Title for the section
    layout: list # Type of content section (list/text)
    content: 
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        link_text: 
        additional_links:
          - title:  
            icon: 
            url: 
          - title: 
            icon: 
            url: 
        quote: 
        description: | # this will include new lines to allow paragraphs
          - Mentored junior engineers in network engineering topics like
             - Networking
             - TCP/IP
             - Security
             - Routing & Switching
             - Wireless Networks
          - Conduct workshops on various topics in the DevOps community like 
             - Automation and Networking
             - Version Control with Git and GitHub
             - Collaboration and Teamwork
             - API Integration with Python 
             - CI/CD Pipeline
             - Yang and Netconf
             - Chatbots and App Integrations  
             

   
  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: New Horizons Learning, Burbank, CA
        sub_title: IT Technical Training   
        caption: 2012 - 2015
        quote: 
        description: | # this will include new lines to allow paragraphs
      - layout: top-middle
        title: Cypress College, Cypress, CA 
        sub_title: University Transfer Student  
        caption: 2008 - 2010
        quote: 
        description: | # this will include new lines to allow paragraphs


  - title: Military   
    layout: list
    content:
      - layout: top-middle
        title: US ARMY 
        sub_title: Specialist
        caption: 2003 - 2006
        quote: 
        description: | # this will include new lines to allow paragraphs
 
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
